// gank request
export const GANK_REQUEST = 'GANK_REQUEST'
export const GANK_SUCCESS = 'GANK_SUCCESS'
export const GANK_FAILURE = 'GANK_FAILURE'

export const GANK_WELFARE_REQUEST = 'GANK_WELFARE_REQUEST'
export const GANK_WELFARE_SUCCESS = 'GANK_WELFARE_SUCCESS'
export const GANK_WELFARE_FAILURE = 'GANK_WELFARE_FAILURE'

export const GANK_EASY_CATEGORY_REQUEST = 'GANK_EASY_CATEGORY_REQUEST'
export const GANK_EASY_CATEGORY_SUCCESS = 'GANK_EASY_CATEGORY_SUCCESS'
export const GANK_EASY_CATEGORY_FAILURE = 'GANK_EASY_CATEGORY_FAILURE'

// gank category
export const GANK_CATEGORY_MODIFY = 'GANK_CATEGORY_MODIFY'

// 闲读
export const GANK_EASY_CATEGORY_MODIFY = 'GANK_EASY_CATEGORY_MODIFY'

export const MENU_CHANGE = 'MENU_CHANGE'